import React, { useEffect, useState } from "react";
import Image from "next/image";
import Head from "next/head";
import Header from "../components/Header";
import Spinner from "../components/Spinner";
import ControlButtons from "../components/ControlButtons";

import { getSpecificMovie } from "../utils/firebase.utlis";

const styles = {
  backgroundContainer: `min-h-[calc(100vh-70px)] text-gray-500 -z-[1] fixed top-0 bottom-0 right-0 left-0 opacity-80`,
  imageTitleContainer: `w-[35vw] min-w-[200px] mb-[20px] mt-50`,
};

const Details = () => {
  const [loading, setLoading] = useState(true);
  const [currentMovie, setCurrentMovie] = useState({});

  useEffect(() => {
    getURLData();
  }, []);

  const getURLData = async () => {
    const queryString = window.location.search;
    const urlParams = new URLSearchParams(queryString);
    setCurrentMovie(await getSpecificMovie(urlParams.get("id")));
    setLoading(false);
  };

  const { backgroundImg, description, subTitle, titleImg } = currentMovie;
  return (
    <>
      <Head>
        <title>{currentMovie && currentMovie.title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {!loading ? (
        <div className='relative min-h-[100vh]'>
          <Header />
          <div className='max-w-2xl detail-title'>
            <div className={styles.backgroundContainer + " mt-16"}>
              <Image
                src={backgroundImg}
                layout='fill'
                objectFit='cover'
                className={styles.imgStyles}
                alt=''
              />
            </div>

            {/* Div for title of movie which is in image */}
            <div className={styles.imageTitleContainer}>
              <Image
                src={titleImg}
                className={
                  styles.imgStyles + " object-contain flex justify-start"
                }
                width={550}
                height={250}
                alt='movie-title'
              />
            </div>

            <ControlButtons />

            <div className='text-white tracking-wide mt-4 pl-12'>
              {subTitle}
            </div>

            <p className='text-white tracking-wide mt-3 max-w-md text-lg pl-12'>
              {description}
            </p>
          </div>
        </div>
      ) : (
        <Spinner />
      )}
    </>
  );
};

export default Details;
