import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import HomePage from '../components/HomePage';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu | Stream Movies & Shows</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <HomePage />
      {/* <Navbar /> */}
      {/* <Content /> */}
      {/* <Footer /> */}
    </div>
  );
}
