import Head from "next/head";

import Header from "../components/Header";
import HomePage from "../components/HomePage";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu | Stream Movies & Shows</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <HomePage />
      <Footer />
    </div>
  );
}
